services:
  traefik:
    build: .
    container_name: traefik
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
    security_opt:
      - no-new-privileges:true
    env_file:
      - .env
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=${DOMAIN}
      - TRAEFIK_CERTIFICATESRESOLVERS_LE_ACME_EMAIL=${LE_EMAIL}
      - TRAEFIK_DASHBOARD_CREDENTIALS=${TRAEFIK_DASHBOARD_CREDENTIALS}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      # config for http
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      # repeat for https
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-dashboard-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=le"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      # dashboard middlewares
      - "traefik.http.middlewares.traefik-dashboard-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"

      # global middlewares
      # 301 redirect to https
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.permanent=true"
      # redirect to www
      - "traefik.http.middlewares.traefik-redirect-to-www.redirectregex.regex=^https?://${DOMAIN}/(.*)"
      - "traefik.http.middlewares.traefik-redirect-to-www.redirectregex.replacement=https://www.${DOMAIN}/$${1}"
      - "traefik.http.middlewares.traefik-redirect-to-www.redirectregex.permanent=true"
      # 301 dotcom redirect
      - "traefik.http.middlewares.traefik-redirect-to-com.redirectregex.regex=^https?://((?:[a-z0-9-]+.)*)${SECOND_LEVEL_DOMAIN}.de(/.*)?"
      - "traefik.http.middlewares.traefik-redirect-to-com.redirectregex.replacement=https://$${1}${SECOND_LEVEL_DOMAIN}.com$${2}"
      - "traefik.http.middlewares.traefik-redirect-to-com.redirectregex.permanent=true"
      # compress output
      - "traefik.http.middlewares.traefik-compress.compress=true"

networks:
  proxy:
    external: true
